/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defense_system_GUI_defences;
import defense_system_util.DefenceObserver;
import defense_system_util.Level;
import defense_system.util.DefenceObsevable;
import defense_system_GUI_main_controller.MainController;


/**
 *
 * @author thili
 */
public class Tank extends javax.swing.JFrame implements DefenceObserver{

    /**
     * Creates new form Tank
     */
    String name;
    private Level lastLv;
    private MainController mainController;
    private DefenceObsevable ob;
      
    public Tank(String name) {
        setTitle("Tank-"+name);
        initComponents();
        this.name=name;
        btnShoot.setEnabled(false);
        btnMissileOperation.setEnabled(false);
        btnRedarOperation.setEnabled(false);
        btnRotateShooting.setEnabled(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider2 = new javax.swing.JSlider();
        lblArea = new javax.swing.JLabel();
        btnShoot = new javax.swing.JButton();
        btnMissileOperation = new javax.swing.JButton();
        btnRedarOperation = new javax.swing.JButton();
        btnRotateShooting = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSend = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        cbPosition = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jsSoilderCount = new javax.swing.JSpinner();
        jsAmmoCount = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jSlider3 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMSGArea = new javax.swing.JTextArea();

        jSlider2.setMajorTickSpacing(20);
        jSlider2.setMinorTickSpacing(10);
        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblArea.setText("Area Not Cleared");

        btnShoot.setText("Shoot");

        btnMissileOperation.setText("Missile Operation");

        btnRedarOperation.setText("Redar Operation");

        btnRotateShooting.setText("Rotate Shooting");

        jScrollPane2.setViewportView(txtSend);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        cbPosition.setText("Position");
        cbPosition.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbPositionStateChanged(evt);
            }
        });
        cbPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPositionActionPerformed(evt);
            }
        });

        jLabel2.setText("Ammo Count");

        jsSoilderCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsSoilderCountStateChanged(evt);
            }
        });

        jsAmmoCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsAmmoCountStateChanged(evt);
            }
        });

        jLabel1.setText("Soildeir Count");

        jSlider3.setMajorTickSpacing(20);
        jSlider3.setMinorTickSpacing(10);
        jSlider3.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider3.setPaintLabels(true);
        jSlider3.setPaintTicks(true);

        txtMSGArea.setEditable(false);
        txtMSGArea.setColumns(20);
        txtMSGArea.setRows(5);
        jScrollPane1.setViewportView(txtMSGArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnRedarOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnRotateShooting, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnMissileOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsSoilderCount, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jsAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cbPosition)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblArea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnMissileOperation)
                                    .addComponent(btnShoot))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRedarOperation)
                                    .addComponent(btnRotateShooting)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jsSoilderCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jsAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbPosition)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSend, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPositionActionPerformed

    private void cbPositionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbPositionStateChanged
        if (!cbPosition.isSelected()) {
            btnRotateShooting.setEnabled(false); 
            btnRedarOperation.setEnabled(false);
            btnMissileOperation.setEnabled(false);
            btnShoot.setEnabled(false);                    
        }else{
            updateButtonVisible(lastLv);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cbPositionStateChanged

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        if(!txtSend.getText().equals("")){
            sendMessagetoAll("You : "+txtSend.getText());
            mainController.printArrivedMessage(name+" : "+txtSend.getText());
            txtSend.setText("");
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void jsSoilderCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsSoilderCountStateChanged
                // TODO add your handling code here:
                ob.updateSoilderCount();
    }//GEN-LAST:event_jsSoilderCountStateChanged

    private void jsAmmoCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsAmmoCountStateChanged
        // TODO add your handling code here:
        ob.updateAmmoCount();
    }//GEN-LAST:event_jsAmmoCountStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMissileOperation;
    private javax.swing.JButton btnRedarOperation;
    private javax.swing.JButton btnRotateShooting;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    private javax.swing.JCheckBox cbPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSpinner jsAmmoCount;
    private javax.swing.JSpinner jsSoilderCount;
    private javax.swing.JLabel lblArea;
    private javax.swing.JTextArea txtMSGArea;
    private javax.swing.JTextArea txtSend;
    // End of variables declaration//GEN-END:variables

    
        @Override
    public void updateButtonVisible(Level lv) {
        lastLv=lv;
        if(cbPosition.isSelected()){
            switch (lv) {
            case LOW:
                btnShoot.setEnabled(true);
                btnMissileOperation.setEnabled(false);
                btnRedarOperation.setEnabled(false);
                btnRotateShooting.setEnabled(false);
                break;
            
            case MEDIUM:
                btnShoot.setEnabled(true);
                btnMissileOperation.setEnabled(true);
                btnRedarOperation.setEnabled(false);
                btnRotateShooting.setEnabled(false);
                break;
                
            case HIGH:
                btnShoot.setEnabled(true);
                btnMissileOperation.setEnabled(true);
                btnRedarOperation.setEnabled(true);
                btnRotateShooting.setEnabled(false);
                break;
                
            case STRONG:
                btnShoot.setEnabled(true);
                btnMissileOperation.setEnabled(true);
                btnRedarOperation.setEnabled(true);
                btnRotateShooting.setEnabled(true);
                
                break;               
            default:
                btnShoot.setEnabled(false);
                btnMissileOperation.setEnabled(false);
                btnRedarOperation.setEnabled(false);
                btnRotateShooting.setEnabled(false);
            }
        
        }
    }
    
    
    
    
    
    @Override
    public void sendMessagetoAll(String msg) {
        txtMSGArea.setText(txtMSGArea.getText()+msg+"\n");
             
    }

    @Override
    public void setArea(boolean Lc) {
        lblArea.setText(Lc?"Area Cleared":"Area Not Cleared");
    }

    @Override
    public void sendMessageToMainControll() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    @Override
    public void setMainController(MainController mainController) {
        this.mainController=mainController;
    }

    @Override
    public int getSoilderCount() {
        return (int)jsSoilderCount.getValue();
    }

    @Override
    public void setDefenceOb(DefenceObsevable ob) {
        this.ob=ob;
    }
    
    
    @Override
    public int getAmmoCount() {
        return (int)jsAmmoCount.getValue();
    }
}
